version: '3.8'

services:
  # Banco de dados PostgreSQL
  db:
    image: postgres:15
    container_name: codeforge_db
    environment:
      POSTGRES_DB: codeforge_db
      POSTGRES_USER: codeforge_user
      POSTGRES_PASSWORD: codeforge_password
    volumes:
      # Persiste dados do banco mesmo quando container for removido
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - codeforge_network

  # Aplicação Django
  web:
    build: .
    container_name: codeforge_web
    environment:
      # Configurações do banco
      DB_NAME: codeforge_db
      DB_USER: codeforge_user
      DB_PASSWORD: codeforge_password
      DB_HOST: db
      DB_PORT: 5432
      # Django
      DEBUG: "True"
      SECRET_KEY: "django-insecure-desenvolvimento-nao-usar-em-producao"
    volumes:
      # Monta o código para desenvolvimento (hot reload)
      - .:/app
      # Persiste arquivos de media
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - codeforge_network

  # Nginx (opcional, para servir arquivos estáticos)
  nginx:
    image: nginx:alpine
    container_name: codeforge_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - codeforge_network

# Volumes para persistir dados
volumes:
  postgres_data:
    driver: local
  media_volume:
    driver: local

# Rede personalizada
networks:
  codeforge_network:
    driver: bridge