# Generated by Django 5.2.4 on 2025-07-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(max_length=300, verbose_name='Descrição Curta')),
                ('description', models.TextField(verbose_name='Descrição Completa')),
                ('is_opensource', models.BooleanField(default=False, verbose_name='Open Source')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='URL do GitHub')),
                ('technology_stack', models.CharField(max_length=200, verbose_name='Stack Tecnológico')),
                ('price_type', models.CharField(choices=[('free', 'Gratuito'), ('paid', 'Pago'), ('custom', 'Sob Consulta')], default='custom', max_length=10, verbose_name='Tipo de Preço')),
                ('features', models.JSONField(default=list, verbose_name='Recursos')),
                ('image_gradient', models.CharField(default='from-purple-500 to-green-400', max_length=100, verbose_name='Gradiente da Imagem')),
                ('icon_text', models.CharField(default='CF', max_length=10, verbose_name='Texto do Ícone')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Produto em Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
