# Generated by Django 5.2.4 on 2025-08-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição/Segmento')),
                ('logo', models.ImageField(help_text='Recomendado: PNG/SVG transparente, proporção 2:1 (ex: 200x100px)', upload_to='clients/logos/', verbose_name='Logo')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('is_featured', models.BooleanField(default=False, help_text='Clientes em destaque aparecem primeiro no carrossel', verbose_name='Cliente Destaque')),
                ('order', models.PositiveIntegerField(default=0, help_text='Números menores aparecem primeiro', verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-is_featured', 'order', 'name'],
            },
        ),
    ]
